on:
  push:
    branches:
      - main
jobs:
  workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: n1hility/cancel-previous-runs@v2
      - uses: actions/checkout@v2
      - run: bash .github/workflows/deploy_to_app_engine.sh '${{ secrets.SA_KEY }}'
